// # Coby
//
// [Coby](http://github.com/pjaspers/coby) is a set of opionated
// categories for Objective-C highly influenced by Ruby (and a bit of
// Rails).
//
// It's far from complete, but highly usable. Most of the methods are
// tested, run `rake test` and you should see all tests passing.
//
// I've tried to document all functions inline, using [docco](http://jashkenas.github.com/docco/)
// which also rocks. In fact this file is generated by it.
//
//
// ## How to use
//
//  1. Find your .pch file
//  2. Import this file
//  3. Make sure to import this file after UIKit and Foundation
//  4. Use the functions in your app.
//
// ## Source
//
// [Additions to NSObject](docs/NSObject+Coby.html)

#import "NSObject+Coby.h"

// [Additions to NSArray](docs/NSArray+Coby.html)

#import "NSArray+Coby.h"

// [Additions to NSDictionary](docs/NSObject+Coby.html)

#import "NSDictionary+Coby.h"

// [Additions to NSString](docs/NSString+Coby.html)

#import "NSString+Coby.h"

