// # Coby
//
// [Coby](http://github.com/pjaspers/coby) is a set of opionated
// categories for Objective-C highly influenced by Ruby (and a bit of
// Rails).
//
// It's far from complete, but highly usable. Most of the methods are
// tested, run `rake test` and you should see all tests passing.
//
// I've tried to document all functions inline, using [docco](http://jashkenas.github.com/docco/)
// which also rocks. In fact this file is generated by it.
//
//
// ## How to use
//
//  1. Find your .pch file
//  2. Import this file
//  3. Make sure to import this file after UIKit and Foundation
//  4. Use the functions in your app.
//
// ## Source
//
// [Additions to NSObject](docs/NSObject+Coby.html)

#import "NSObject+Coby.h"

// [Additions to NSArray](docs/NSArray+Coby.html)

#import "NSArray+Coby.h"

// [Additions to NSDictionary](docs/NSObject+Coby.html)

#import "NSDictionary+Coby.h"

// [Additions to NSString](docs/NSString+Coby.html)

#import "NSString+Coby.h"

// ## Common Macros

//      CGRect aRect = (CGRect){ 0,1,2,3};
//      RectLog(aRect)
//        => @"aRect rect: {0,1,2,3}"
//
#define RectLog(x) NSLog(@"%s rect: %@",#x, NSStringFromCGRect(x.frame))

// Blatantly picked up from [Wil Shipley](http://blog.wilshipley.com/2005/10/pimp-my-code-interlude-free-code.html)
//
// > Essentially, if you're wondering if an NSString or NSData or
// > NSAttributedString or NSArray or NSSet has actual useful data in
// > it, this is your macro. Instead of checking things like
// > `if (inputString == nil || [inputString length] == 0)` you just
// > say, "if (IsEmpty(inputString))".
//
// It rocks.
static inline BOOL IsEmpty(id thing) {
    return thing == nil
	|| ([thing isEqual:[NSNull null]]) // addition for things like coredata
	|| ([thing respondsToSelector:@selector(count)]
        && [thing performSelector:@selector(count)] == 0)
	|| ([thing respondsToSelector:@selector(length)]
        && [thing performSelector:@selector(length)] == 0);
}

// The inverse for IsEmpty
static inline BOOL IsPresent(id thing) {
    return !IsEmpty(thing);
}

static inline BOOL IsInSimulator() {
#if TARGET_IPHONE_SIMULATOR
	return YES;
#endif
	return NO;
}

// A check to see if we're running on an iPad.
// Picked up [here](http://cocoawithlove.com/2010/07/tips-tricks-for-conditional-ios3-ios32.html)
static inline BOOL IsIPad() {
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 30200
    if ([[UIDevice currentDevice] respondsToSelector:@selector(userInterfaceIdiom)] && [[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad){
		return YES;
	} else
#endif
    {
       	return NO;
    }
}
